name: Sonar Node.js CI Tests

on: [push]

jobs:
  sonar:
    os: [ubuntu-latest]
    node-version: [12.x, 14.x]
  build:
    runs-on: ${{sonar.os}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test


