name: Sonar Node.js CI Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/Sonar

    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Run build
      run: yarn
    - name: Run tests
      run: yarn test
